source: "E:\\go\\src\\TemplateFactory\\source"
#source: "/Users/haoshuo/TemplateFactory/source/source.go"

ent:
  production: true
  path: ""
  overwrite: false

proto:
  production: true
  path: ""
  overwrite: false

data:
  production: true
  path: ""
  test: true
  overwrite: false

biz:
  production: true
  path: ""
  test: true
  overwrite: false
